# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      
      - uses: Azure/cli@v1
        id: bicep
        with: 
          # Specify the script here
          inlineScript: |
            environment=$(az deployment group create -g ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file $GITHUB_WORKSPACE/infrastructure/infrastructure.bicep --query properties.outputs.environment.value)
            echo "::set-output name=environment::$environment"
        
      - uses: Azure/powershell@v1
        with:
          # Specify the Az PowerShell script here.
          inlineScript: |
            & "$env:GITHUB_WORKSPACE/infrastructure/dataplane_setup.ps1" -Environment ${{ steps.bicep.outputs.environment }} -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }}
          # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: latest
          # If this is true, this task will fail if any errors are written to the error pipeline, or if any data is written to the Standard Error stream.
          failOnStandardError: true
          
      - uses: Azure/cli@v1
        with: 
          # Specify the script here
          inlineScript: az storage blob sync -c "\$web" -s $GITHUB_WORKSPACE/src --account-name stvfizzweb${{ steps.bicep.outputs.environment }}

      - uses: Azure/cli@v1
        with: 
          # Specify the script here
          inlineScript: az cdn endpoint purge -n cdn-endpoint-vaporfizzweb-${{ steps.bicep.outputs.environment }} --profile-name cdn-vaporfizzweb-${{ steps.bicep.outputs.environment }} -g ${{ secrets.AZURE_RESOURCE_GROUP }} --content-paths "/*"
